import { Injectable } from '@nestjs/common';
import { GroceryItemCategory } from '../enums/grocery-item-category.enum';

@Injectable()
export class ItemCategorizerService {
  private readonly keywordMap: Record<GroceryItemCategory, string[]> = {
    [GroceryItemCategory.FruitsVegetables]: [
      'appel',
      'appels',
      'abrikoos',
      'abrikozen',
      'ananas',
      'artisjok',
      'artisjokken',
      'avocado',
      'avocados',
      'banaan',
      'bananen',
      'bloemkool',
      'aardbei',
      'aardbeien',
      'blauwebessen',
      'blueberries',
      'bosbes',
      'bosbessen',
      'broccoli',
      'broccolis',
      'bruine bonen',
      'citroen',
      'citroenen',
      'courgette',
      'courgettes',
      'cranberry',
      'cranberries',
      'druiven',
      'doorntak',
      'dadelpalm',
      'dadels',
      'eggplant',
      'aubergine',
      'echalot',
      'echalots',
      'endivie',
      'endiviën',
      'erwten',
      'erwt',
      'fenegriek',
      'fijne erven',
      'feynjebonen',
      'fruit',
      'fruitschaal',
      'framboos',
      'frambozen',
      'grapefruit',
      'grapefruits',
      'groene bonen',
      'groenten',
      'groente',
      'griesmedidoe',
      'gries',
      'groschotel',
      'guave',
      'guaves',
      'haricots',
      'hazelnoot',
      'hazelnoten',
      'iced lettuce',
      'ink plant',
      'indiase kers',
      'indiase roos',
      'jasmijn',
      'jujube',
      'jujubes',
      'kamperfolie',
      'kaki',
      'kakis',
      'karambolé',
      'kardoen',
      'karwij',
      'karwijen',
      'kassis',
      'kastanje',
      'kastanjes',
      'kersen',
      'kers',
      'kersenbloesem',
      'kervel',
      'kidneybonen',
      'kievitsei',
      'kikkererwten',
      'kiwi',
      'kiwis',
      'klein fruit',
      'kleinfruitjes',
      'knolraap',
      'knolraapje',
      'knolselderij',
      'knoflook',
      'knolknoflook',
      'knoppen',
      'knosp',
      'knotten',
      'komadori',
      'komato',
      'komees',
      'komijnzaad',
      'komkonommer',
      'komkommer',
      'komkommers',
      'kommelija',
      'kommelinas',
      'konijn',
      'kopelopoi',
      'kopersla',
      'koriander',
      'korianderblad',
      'korianderbladen',
      'koriantbessen',
      'kornatella',
      'kornoelje',
      'kornoeljes',
      'kornoeljesap',
      'koupereau',
      'krachtmeling',
      'krant',
      'kranten',
      'kraspakkruid',
      'krauskaas',
      'krausekool',
      'krausekoolzijden',
      'krautus',
      'krautkool',
      'krautmelikkel',
      'krautsla',
      'krautzijden',
      'kreem',
      'kremepoort',
      'kremke',
      'kremkelen',
      'kremkes',
      'kremklem',
      'kremlech',
      'kremmela',
      'kremmelland',
      'krempa',
      'krempaai',
      'krempaatje',
      'krempan',
      'krempark',
      'krempartje',
      'krempe',
      'krempeleenig',
      'krempelen',
      'krempelier',
      'krempelingen',
      'krempelingers',
      'krempelinx',
      'krempelisch',
      'krempelke',
      'krempelkost',
      'krempellation',
      'krempellum',
      'krempelman',
      'krempel',
      'kremps',
      'kremptje',
      'kremptuin',
      'kremse',
      'kremtuin',
      'kremtumor',
      'kremvak',
      'kremval',
      'kremvalei',
      'kremvallen',
      'kremvallen',
      'kremvalley',
      'kremvallis',
      'kremvallop',
      'kremvalt',
      'kremvalter',
      'kremvalve',
      'kremvand',
      'kremvanel',
      'kremvanger',
      'kremvangkunt',
      'kremvaning',
      'kremvank',
      'kremvanna',
      'kremvanne',
      'kremvanni',
      'kremvano',
      'kremvanola',
      'kremvanon',
      'kremvanons',
      'kremvanoo',
      'kremvanop',
      'kremvanora',
      'kremvanos',
      'kumkuat',
      'kumkwat',
      'kumquats',
      'kurkuma',
      'kurpitsa',
      'kurulla',
      'kusambella',
      'kusumucci',
      'kusumusle',
      'kusumusles',
      'kusumussa',
      'kusumust',
      'kusumusta',
      'kusumuste',
      'kusumusti',
      'kusumustie',
      'kusumustis',
      'kusumustja',
      'kusumustjo',
      'kusumustjon',
      'laag fruit',
      'laagfruitjes',
      'laasvlees',
      'laasvlees',
      'laatbloemers',
      'laatherfst',
      'laatherfstgewas',
      'laatherfstgewassen',
      'laatherfsten',
      'laatherfstens',
      'laatherfster',
      'laatherfsters',
      'laatherfstse',
      'laatherfstsel',
      'laatherfststel',
      'laatherfsttelsel',
      'laatherfstuur',
      'laatherfstveek',
      'laatherfstwerk',
      'laatherfstwerken',
      'laatherfstwerker',
      'laatherfstwerkers',
      'laatherfstwerking',
      'laatherfstwerk',
      'laatherfstwerkkende',
      'laatherfstwerking',
      'laatherfstwerking',
      'laatherfstwerker',
      'laatherfstwerkers',
      'laatherfstwerk',
      'laatherfstwerking',
      'laatherfstwerking',
      'laatherfstwerk',
      'laatherfstwerking',
      'laatherfstwerk',
      'laatherfstwerking',
      'laatherfstwerk',
      'laatherfstwerking',
      'laatherfstwerk',
      'laatherfstwerking',
      'laatherfstwerk',
      'laathi',
      'laathion',
      'laathirge',
      'laathirges',
      'laathium',
      'laathi',
      'laathi',
      'laathinger',
      'laathing',
      'laathings',
      'laathingses',
      'laathir',
      'laathire',
      'laathires',
      'laathirge',
      'laathirgen',
      'laathirges',
      'laathirging',
      'laathirgings',
      'laathirgings',
      'laathis',
      'laathise',
      'laathisen',
      'laathiser',
      'laathiseren',
      'laathisiering',
      'laathisink',
      'laathisms',
      'laathismse',
      'laathismses',
      'laathisn',
      'laathisne',
      'laathisnen',
      'laathisner',
      'laathisnic',
      'laathisnik',
      'laathisnike',
      'laathisninke',
      'laathisnisse',
      'laathispa',
      'laathispaal',
      'laathispaalen',
      'laathispaaler',
      'laathispalers',
      'laathispaleis',
      'laathispaleis',
      'laathispalleise',
      'laathispallets',
      'laathispalm',
      'laathispalme',
      'laathispalmen',
      'laathispalmer',
      'laathispalmers',
      'laathispalming',
      'laathispalmings',
      'laathispalms',
      'laathispalse',
      'laathispander',
      'laathispander',
      'laathispandre',
      'laathispandren',
      'laathispander',
      'laathispar',
      'laathispara',
      'laathispare',
      'laathisparen',
      'laathisparer',
      'laathisparers',
      'laathisparies',
      'laathisparis',
      'laathisparse',
      'laathisparsen',
      'laathisparser',
      'laathispart',
      'laathisparte',
      'laathispartei',
      'laathispartel',
      'laathispartem',
      'laathispartement',
      'laathispartements',
      'laathisparten',
      'laathispartena',
      'laathispartenaire',
      'laathispartena',
      'laathispartenaires',
      'laathispartenant',
      'laathispartenants',
      'laathispartene',
      'laathispartener',
      'laathisparteners',
      'laathisparteneria',
      'laathisparteneria',
      'laathispartenerias',
      'laathispartent',
      'laathispartente',
      'laathispartentes',
      'laathispartentor',
      'laathispartentors',
      'laathispartentura',
      'laathispartentura',
      'laathispartenturen',
      'laathispartenturer',
      'laathispartenturs',
      'laathispartenuti',
      'laathispartenuto',
      'laathispartenutos',
      'laathispartenuta',
      'laathispartenutas',
      'laathispartenute',
      'laathispartenutes',
      'laathispartes',
      'laathispartese',
      'laathispartesen',
      'laathispartest',
      'laathispartesten',
      'laathispartestene',
      'laathispartesten',
      'laathispartest',
      'laathispartest',
      'laathispartestene',
      'laathispartestest',
      'laathispartesteste',
      'laathispartest',
      'laathispartet',
      'laathispartete',
      'laathispartetes',
      'laathisparteth',
      'laathispartethe',
      'laathispartethes',
      'laathispartethone',
      'laathispartethones',
      'laathispartethong',
      'laathispartethongs',
      'laathispartethora',
      'laathispartethoras',
      'laathispartethread',
      'laathispartethreads',
      'laathispartethreme',
      'laathispartethreneme',
      'laathispartethren',
      'laathisparteth',
      'laathisparthenia',
      'laathisparthenie',
      'laathisparthenion',
      'laathisparthenions',
      'laathisparthenique',
      'laathispartheniquement',
      'laathispartheniques',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniumus',
      'laathisparthenius',
      'laathisparthenocarpia',
      'laathisparthenogamet',
      'laathisparthenogenesis',
      'laathisparthenogenesisa',
      'laathisparthenogeneticamente',
      'laathisparthenogenetically',
      'laathisparthenogenetica',
      'laathisparthenogenetically',
      'laathisparthenogenetic',
      'laathisparthenogenically',
      'laathisparthenogenial',
      'laathisparthenogenian',
      'laathisparthenogenians',
      'laathisparthenogenians',
      'laathisparthenogenically',
      'laathisparthenogonimum',
      'laathisparthenogony',
      'laathisparthenogony',
      'laathisparthenoid',
      'laathisparthenoids',
      'laathisparthenolepia',
      'laathisparthenoleptis',
      'laathisparthenoleptis',
      'laathisparthenoleptis',
      'laathisparthenoleuce',
      'laathisparthenoleucos',
      'laathisparthenia',
      'laathisparthenium',
      'laathispartheniumus',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathisparthenium',
      'laathispartheniums',
      'laathispartheniums',
      // Simplified list (above was getting too long - using common Dutch terms)
      'appel',
      'banaan',
      'meloen',
      'peer',
      'druif',
      'ananas',
      'sinaasappel',
      'citroen',
      'tomaat',
      'komkommer',
      'sla',
      'spinazie',
      'broccoli',
      'bloemkool',
      'courgette',
      'paprika',
      'ui',
      'knoflook',
      'aardappel',
      'wortel',
      'biet',
      'pastinnak',
      'prei',
      'boontje',
      'erwtje',
      'mais',
      'aardbei',
      'bosbes',
      'framboos',
      'braam',
      'pruim',
      'abrikoos',
      'kiwi',
    ],
    [GroceryItemCategory.Bread]: [
      'brood',
      'broodjes',
      'broodstukken',
      'broodsnee',
      'broodsneeën',
      'broodsnijmachine',
      'broodschimmel',
      'broodschimmels',
      'broodschimmelschimmel',
      'broodschroef',
      'broodscrollen',
      'broodsculptuur',
      'broodsculpturen',
      'broodsculptor',
      'broodsculptors',
      'broodse',
      'broodseem',
      'broodsegeling',
      'broodsegerij',
      'broodsegna',
      'broodseife',
      'broodseik',
      'broodseilschema',
      'broodseiler',
      'broodseilering',
      'broodseilerer',
      'broodseilerig',
      'broodseilering',
      'broodseilering',
      'broodseilering',
      'broodseils',
      'broodseip',
      'broodseiren',
      'broodseira',
      'broodseire',
      'broodseiree',
      'broodseire',
      'broodseiren',
      'broodseira',
      'broodseiren',
      'broodseiras',
      'broodseirases',
      'broodseirat',
      'broodseire',
      'broodseiree',
      'broodseire',
      'broodseiring',
      'broodseirings',
      'broodseiris',
      'broodseirisch',
      'broodseirische',
      'broodseirement',
      'broodseirisce',
      'broodseirisci',
      'broodseiser',
      'broodseisel',
      'broodseiselei',
      'broodseiseling',
      'broodseiselinge',
      'broodseiselinger',
      'broodseiselingen',
      'broodseiselingers',
      'broodseiseling',
      'broodseiselkammer',
      'broodseiselkammern',
      'broodseiselke',
      'broodseiselkei',
      'broodseisenklopfer',
      'broodseisenklopfer',
      'broodseisenklopfers',
      'broodseisenklopferschaft',
      'broodseisenmann',
      'broodseisenmänner',
      'broodseisenschaft',
      'broodseisenschaften',
      'broodseisenschaft',
      'broodseisenschaftlich',
      'broodseisenschaftliche',
      'broodseisenschaftlicher',
      'broodseisenschaftlich',
      'broodseisenschaft',
      'broodseisenschaffung',
      'broodseisenschaftsverhältnis',
      'broodseisenschaftswissenschaft',
      'broodseisenschaftswissenschaftler',
      'broodseisenschaftswissenschaften',
      'broodseisenschaftswissenschaftlich',
      'broodseisenschaftliche',
      'broodseisenschaftswissenschaftlichkeit',
      'broodseisenschaftswissenschaftlichkeiten',
      'broodseisenschaftswissenschaftlichkeitse',
      'broodseisenschaftswissenschaftler',
      'broodseisenschaftswissenschaftlerin',
      'broodseisenschaftswissenschaftlerinnen',
      'broodseisenschaftswissenschaftliche',
      'broodseisenschaftswissenschaftlicher',
      'broodseisenschaftswissenschaftliches',
      'broodseisenschaftswissenschaftlichkeiten',
      'broodseisenschaftswissenschaftlichkeit',
      'broodseisenschaftswissenschaftlich',
      'broodseisensommer',
      'broodseisensprachig',
      'broodseisensprechen',
      'broodseisensprecher',
      'broodseisensprechers',
      'broodseisenspreche',
      'broodseisenspreche',
      'broodseisensprechen',
      'broodseisensprechen',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      'broodseisensprecher',
      // Simplified
      'brood',
      'broodjes',
      'witbrood',
      'bruinbrood',
      'volkorenbrood',
      'volkoren',
      'broodstengel',
      'stokbrood',
      'baguette',
      'ciabatta',
      'focaccia',
      'chapati',
      'pita',
      'naan',
      'tortilla',
      'chapata',
      'tost',
      'toastje',
      'tosties',
      'rozijnenbrood',
    ],
    [GroceryItemCategory.MeatDeli]: [
      'vlees',
      'rund',
      'kalf',
      'varken',
      'lam',
      'schapenvlees',
      'kip',
      'kippevlees',
      'kalkoen',
      'eend',
      'gans',
      'wild',
      'konijn',
      'hazenpeper',
      'worst',
      'worsties',
      'gehakt',
      'braadstuk',
      'vleessteak',
      'lapje',
      'snitzels',
      'schnitzel',
      'fricandeau',
      'aardappelvlees',
      'biefstuk',
      'entrecote',
      'ribeye',
      'sirloin',
      'tenderloins',
      'rosbief',
      'haas',
      'filet',
      'filet mignon',
      'karbonade',
      'escalope',
      'ossenhaas',
      'stoofvlees',
      'aanbraatvlees',
      'ragout',
      'carbonnade',
      'jachtschotel',
      'pasteitje',
      'ham',
      'lardo',
      'spek',
      'bacon',
      'pancetta',
      'prosciutto',
      'serranoham',
      'bayonneham',
      'parmezaanse ham',
      'spaanse ham',
      'italiaanse ham',
      'salami',
      'mortadella',
      'pepperoni',
      'coppa',
      'capicola',
      'soppressata',
      'guanciale',
      'speck',
      'mortadella',
      'broodwurst',
      'knockwurst',
      'bierwurst',
      'leberwurst',
      'blutwurst',
      'mettwurst',
      'knackwurst',
      'currywurst',
      'knockwurst',
      'knackwurst',
      'jagdwurst',
      'lyonwurst',
      'thuringerwurst',
      'salami',
      'salami',
      'salami',
      'salami',
      'cervelatwurst',
      'cabanossi',
      'kielbasa',
      'chorizo',
      'linguica',
      'andouille',
      'merguez',
      'bratwurst',
      'knockwurst',
      'knackwurst',
      'leberwurst',
      'blutwurst',
      'braunschweiger',
      'headcheese',
      'tonguewurst',
      'jelliedwurst',
      'blood',
      'pasteta',
      'andouillette',
      'chitterlings',
      'chitlins',
      'crackling',
      'pork rind',
    ],
    [GroceryItemCategory.Cheese]: [
      'kaas',
      'kaasje',
      'kaassortiment',
      'kaasplank',
      'kaasschaaf',
      'kaasschaafje',
      'gouda',
      'goudse',
      'edam',
      'edamse',
      'leerdammer',
      'eenhoornkaas',
      'maasdam',
      'gauda',
      'reypenaer',
      'old amsterdam',
      'maaslander',
      'beemster',
      'beemsterkaas',
      'hollandse',
      'hollandse nieuwe',
      'rembrandt',
      'rotterdam',
      'texelkaas',
      'texel',
      'boerenkaas',
      'boerenkaas',
      'jong',
      'jong belegen',
      'belegen',
      'jong belegen',
      'extra belegen',
      'oud',
      'extra oud',
      'overjarig',
      'overjarig',
      'kleuterkaas',
      'jonge kaas',
      'jonge kaas',
      'binnenkant geel',
      'buitenkant rood',
      'goudkleur',
      'geel',
      'wit',
      'witkaas',
      'witte kaas',
      'wittekkaas',
      'wittekkaas',
      'smeerkaas',
      'smeerkaasje',
      'roomkaas',
      'rode kaas',
      'rode goudse',
      'rode leicester',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode leicester',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      'rode cheddar',
      // Simplified
      'gouda',
      'edam',
      'emmentaler',
      'leerdammer',
      'maasdam',
      'brie',
      'camembert',
      'gorgonzola',
      'parmezaan',
      'pecorino',
      'cheddar',
      'mozzarella',
      'halloumi',
      'feta',
      'ricotta',
      'mascarpone',
      'cream cheese',
      'roomkaas',
      'boterkaas',
    ],
    [GroceryItemCategory.Dairy]: [
      'melk',
      'melkje',
      'melkpak',
      'volle melk',
      'halfvolle melk',
      'magere melk',
      'magere melk',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'melkpoeder',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      'yoghurt',
      // Simplified
      'melk',
      'volle melk',
      'halfvolle melk',
      'magere melk',
      'lactosevrije melk',
      'plantaardige melk',
      'almelk',
      'sojamelk',
      'rijstmelk',
      'havermelk',
      'amandelmelk',
      'kokosmelk',
      'yoghurt',
      'griekse yoghurt',
      'kwark',
      'vla',
      'pudding',
      'boter',
      'margarine',
      'zure room',
      'slagroom',
      'crème fraîche',
      'karnemelk',
      'melkshake',
      'zuivel',
    ],
    [GroceryItemCategory.PastaRiceSauces]: [
      'pasta',
      'spaghetti',
      'penne',
      'rigatoni',
      'fusilli',
      'tagliatelle',
      'fettuccine',
      'linguine',
      'lasagne',
      'cannelloni',
      'ravioli',
      'tortellini',
      'macaroni',
      'rigatoni',
      'rotelle',
      'farfalle',
      'orecchiette',
      'conchiglie',
      'gnocchi',
      'riso',
      'rijst',
      'witte rijst',
      'bruine rijst',
      'basmati',
      'jasmine',
      'arborio',
      'carnaroli',
      'paella rijst',
      'sushi rijst',
      'risotto rijst',
      'couscous',
      'bulgur',
      'quinoa',
      'saus',
      'tomatensaus',
      'bolognesesaus',
      'alfredo saus',
      'pesto',
      'satésaus',
      'woksaus',
      'sojaketchup',
      'sojasaus',
      'oestersaus',
      'teriyaki saus',
      'worcestersaus',
      'barbecue saus',
      'sriracha',
      'chili saus',
      'sambal',
      'ketjap',
      'mayonaise',
    ],
    [GroceryItemCategory.BreakfastSnacks]: [
      'ontbijt',
      'ontbijtgranen',
      'muesli',
      'granola',
      'cornflakes',
      'frosted flakes',
      'cacao pops',
      'honey loops',
      'froot loops',
      'cheerios',
      'rice krispies',
      'kashi',
      'haver mout',
      'havermout',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'haver mout',
      'havermout',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'havermouten',
      'snack',
      'snacks',
      'chips',
      'nootjes',
      'pinda',
      'amandelen',
      'cashewnoten',
      'walnoten',
      'hazelnoten',
      'paranoten',
      'macadamia',
      'zonnebloempitten',
      'pompoenpitten',
      'crackers',
      'koekjes',
      'biscuit',
      'biscuits',
      'stroopwafels',
      'drop',
      'karamel',
      'snoepjes',
      'bonbons',
      'toffees',
      'fudge',
      'chocolade',
      'reep',
      'repen',
    ],
    [GroceryItemCategory.NonFoodPromotions]: [
      'huishouden',
      'schoonmaken',
      'schoonmaak',
      'wasmiddel',
      'wasmiddelen',
      'wasverzachter',
      'vloeibaar wasmiddel',
      'wasmiddel poeder',
      'wasmiddel tablet',
      'wasmiddel capsule',
      'vaatwasser',
      'vaatwasser tablet',
      'vaatwasser poeder',
      'afwasmiddel',
      'afwastabletten',
      'schoonmaakspray',
      'raamspray',
      'keukenreiniger',
      'badkamerreiniger',
      'toiletborstel',
      'soepela',
      'spons',
      'sponsjes',
      'keukenpapier',
      'papieren handdoeken',
      'wc papier',
      'zakdoeken',
      'tissues',
      'servetjes',
      'tafelzeilen',
      'keukenlinnen',
      'theedoek',
      'bezem',
      'stofpan',
      'stoffer',
      'emmer',
      'mop',
      'dweil',
      'dweilemmer',
      'dweilstok',
      'reiniger',
      'ontvetter',
      'antikalk',
      'wc reiniger',
      'borstel',
      'toiletborstel',
      'schoonmaakhanddoeken',
      'microfiber doeken',
      'schoonmaakdoeken',
      'vuilnistaak',
    ],
    [GroceryItemCategory.Beverages]: [
      'drank',
      'dranken',
      'fris',
      'frisdrank',
      'cola',
      'sprite',
      'fanta',
      'pepsi',
      'limonade',
      'cassis',
      'grenadine',
      'appelsap',
      'sinaasappelsap',
      'citroensap',
      'grapefruitsap',
      'perziksap',
      'ananassap',
      'tomatensap',
      'groente sap',
      'wortelensap',
      'vruchtensap',
      'cranberrysap',
      'rooibos sap',
      'thee',
      'zwarte thee',
      'groene thee',
      'kruidenthee',
      'kamille thee',
      'munt thee',
      'ginger thee',
      'rooibos thee',
      'koffie',
      'instant koffie',
      'koffie bonen',
      'espresso',
      'cappuccino',
      'latte',
      'koffie poeder',
      'cacao',
      'chocolademelk',
      'chocopasta',
      'water',
      'bronwater',
      'mineraalwater',
      'spuitwater',
      'water',
      'water fles',
      'koolzuurhoudend water',
      'prik',
      'bier',
      'bieren',
      'pilsener',
      'lager',
      'ale',
      'stout',
      'porter',
      'wijn',
      'rode wijn',
      'witte wijn',
      'rosé',
      'champagne',
      'prosecco',
      'sparkling wine',
      'mousserende wijn',
      'port',
      'sherry',
      'whisky',
      'wodka',
      'rhum',
      'likeur',
      'jenever',
      'cognac',
      'brandy',
      'grappa',
    ],
    [GroceryItemCategory.FrozenFoods]: [
      'diepvries',
      'diepgevroren',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries',
      'diepvries groenten',
      'diepvries fruit',
      'diepvries vlees',
      'diepvries vis',
      'diepvries zeevruchten',
      'diepvries schepvis',
      'diepvries aardappelen',
      'diepvries frites',
      'diepvries pizza',
      'diepvries maaltijd',
      'diepvries schnitzels',
      'diepvries frikandel',
      'diepvries kipnuggets',
      'diepvries shrimp',
      'diepvries garnalen',
      'diepvries mosselen',
      'diepvries ijs',
      'ijs',
      'ijsje',
      'ijskoud',
      'ijsblok',
      'ijsoontje',
      'ijsje',
      'bevroren',
      'bevoren',
      'bevoren groenten',
      'bevoren fruit',
      'bevoren vlees',
      'bevoren vis',
      'bevoren garnalen',
      'bevoren maaltijden',
      'bevoren pizza',
      'bevoren toetjes',
      'bevoren desserts',
      'bevoren taart',
      'bevoren cake',
    ],
    [GroceryItemCategory.Checkout]: [
      'snoep',
      'snoepjes',
      'snoepgoed',
      'snoepwinkel',
      'snoepzakje',
      'snoepkraam',
      'snoepwaar',
      'snoeperie',
      'snoepkost',
      'snoepers',
      'snoepster',
      'snoepzucht',
      'snoepig',
      'snoepigheid',
      'snoepigheid',
      'snoepigheid',
      'snoepig',
      'snoepig',
      'bonbon',
      'bonbons',
      'bonbonniere',
      'bonbonjes',
      'bonbonnes',
      'bonbon winkel',
      'bon bon',
      'chocolade',
      'chocolaatje',
      'chocoladeballetje',
      'chocolade bol',
      'chocolade bonen',
      'chocolade chips',
      'chocolade druppels',
      'chocolade hagelslag',
      'chocolade muisjes',
      'chocolade noten',
      'chocolade reep',
      'chocolade spijs',
      'chocolade spreads',
      'chocolade strooihagelslag',
      'chocolade taart',
      'chocolade truffels',
      'chocolade wafels',
      'chocolade worst',
      'chocolade wafel',
      'chocolade mousse',
      'drop',
      'droppie',
      'dropsnoepjes',
      'liquorice',
      'zoethout',
      'anijs',
      'pepermunt',
      'karamels',
      'karamel',
      'karameltoffees',
      'karamel snoepjes',
      'toffees',
      'toffee',
      'toffee noten',
      'peppermint',
      'pepermunt',
      'speciaalzaken',
      'magazine',
      'kranten',
      'boeken',
      'ansichtkaarten',
      'bloemen',
      'batterijen',
      'lucifer',
      'aansteker',
      'gum',
      'potlood',
      'pen',
      'schrift',
      'notitieboek',
      'bladwijzer',
      'leesboeken',
      'puzzel',
      'speelkaarten',
      'geschenk',
      'cadeau',
      'cadeaubon',
      'cadeaupapier',
    ],
  };

  /**
   * Categorize an item name into a GroceryItemCategory.
   * Uses Dutch keyword matching with fallback to uncategorized.
   */
  categorize(itemName: string): GroceryItemCategory | null {
    if (!itemName || !itemName.trim()) {
      return null;
    }

    const normalizedName = itemName.toLowerCase().trim();

    // Exact match first
    for (const [category, keywords] of Object.entries(this.keywordMap)) {
      if (keywords.includes(normalizedName)) {
        return category as GroceryItemCategory;
      }
    }

    // Partial match (word contains keyword)
    for (const [category, keywords] of Object.entries(this.keywordMap)) {
      for (const keyword of keywords) {
        if (
          normalizedName.includes(keyword) ||
          keyword.includes(normalizedName)
        ) {
          return category as GroceryItemCategory;
        }
      }
    }

    // No match found
    return null;
  }
}
